spring:
  application:
    name: spring-data-es-sample
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - http://localhost:9200
            - http://localhost:8200
            - http://localhost:7200
