spring:
  application:
    name: spring-cache-sample
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-wait: 100ms
    password: 123456
server:
  port: 9090
  servlet:
    context-path: /spring-cache
