#################################### common config : ####################################
spring.application.name: spring-data-monogo-sample
# \u5E94\u7528\u670D\u52A1web\u8BBF\u95EE\u7AEF\u53E3
server.port: 10002

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
